version: "3"
services: 
    aria2:
        image: aria
        volumes: 
            - ~/Downloads/aria2:/data
            - ./html:/var/www/html
        restart: always
        ports: 
            - 6800:6800
            - 8080:80
